"""Lacuna live demo — Streamlit UI for mechanism classification.

Drag a CSV in, hit Analyze, get a green/yellow/red verdict alongside the
model's intermediate work. Pure-Python helpers live in `demo/pipeline.py`
so this file can stay focused on UI.

Run:
    streamlit run demo/app.py
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from demo.pipeline import (
    ACTION_LABELS,
    CHECKPOINT_ENV,
    CLASS_NAMES,
    MODEL_DEFAULTS,
    build_model,
    cross_column_corr,
    csv_to_dataset,
    load_metadata,
    missingness_overview,
    resolve_checkpoint,
    run_model,
)


DEFAULT_CHECKPOINT = PROJECT_ROOT / "demo" / "model.pt"

ACTION_COLORS = {0: "#2ecc71", 1: "#f1c40f", 2: "#e74c3c"}
ACTION_HEADLINES = {
    0: "Safe — missingness looks random",
    1: "Use caution — missingness depends on observed data",
    2: "Stop — missingness likely depends on the missing values",
}
ACTION_BODIES = {
    0: (
        "Complete-case analysis is valid. Simple imputation "
        "(mean/median, listwise deletion) is acceptable."
    ),
    1: (
        "Use multiple imputation (MICE, Amelia II) or likelihood-based "
        "methods (EM, full-information maximum likelihood)."
    ),
    2: (
        "Use sensitivity analysis, selection models (Heckman), or "
        "pattern-mixture models. Standard imputation may be biased."
    ),
}


@st.cache_resource(show_spinner=False)
def _load_model_cached(path: str):
    return build_model(path)


# =============================================================================
# UI helpers
# =============================================================================

TRAFFIC_LIGHT_CSS = """
<style>
.lacuna-light-card {
    border-radius: 18px;
    padding: 28px 32px;
    margin: 12px 0;
    color: white;
    box-shadow: 0 6px 24px rgba(0,0,0,0.18);
}
.lacuna-light-label {
    font-size: 14px;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    opacity: 0.85;
    margin-bottom: 6px;
}
.lacuna-light-headline {
    font-size: 32px;
    font-weight: 700;
    margin: 0 0 10px 0;
    line-height: 1.15;
}
.lacuna-light-body {
    font-size: 16px;
    opacity: 0.95;
    line-height: 1.45;
}
.lacuna-confidence {
    margin-top: 14px;
    font-size: 13px;
    opacity: 0.85;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}
</style>
"""


def render_traffic_light(result: dict) -> None:
    action_id = result["action_id"]
    color = ACTION_COLORS[action_id]
    label = ACTION_LABELS[action_id]
    headline = ACTION_HEADLINES[action_id]
    body = ACTION_BODIES[action_id]
    conf = result["confidence"] * 100
    pred = result["predicted_class_name"]

    st.markdown(TRAFFIC_LIGHT_CSS, unsafe_allow_html=True)
    st.markdown(
        f"""
        <div class="lacuna-light-card" style="background: {color};">
            <div class="lacuna-light-label">Recommendation · {label}</div>
            <div class="lacuna-light-headline">{headline}</div>
            <div class="lacuna-light-body">{body}</div>
            <div class="lacuna-confidence">
                predicted mechanism: {pred} · confidence: {conf:.1f}%
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# =============================================================================
# Page
# =============================================================================

st.set_page_config(
    page_title="Lacuna — Missing Data Mechanism Classifier",
    page_icon="🚦",
    layout="wide",
)

st.title("Lacuna")
st.caption(
    "**Posterior probability** that your tabular dataset's missingness was generated by "
    "MCAR (random), MAR (depends on observed), or MNAR (depends on the missing values themselves). "
    "Calibrated under domain-conditioned priors — not a categorical verdict."
)
st.info(
    "**Scope contract.** Lacuna-Survey is calibrated for self- or interviewer-administered "
    "**survey questionnaires**. It will return a posterior on any tabular input, but predictions "
    "on non-survey data (sensor logs, medical records, financial panels, etc.) are *not* validated "
    "and may be confidently wrong. The scope decision is yours — Lacuna does not police it.",
    icon="📋",
)

# ----- Sidebar: model info -----
with st.sidebar:
    st.subheader("Model")
    ckpt_path = resolve_checkpoint(DEFAULT_CHECKPOINT)
    if not ckpt_path.exists():
        st.error(
            f"No checkpoint at `{ckpt_path}`. Set `{CHECKPOINT_ENV}` or "
            f"copy a `.pt` file to `demo/model.pt`."
        )
        st.stop()

    try:
        model, n_params = _load_model_cached(str(ckpt_path))
    except Exception as e:
        st.error(f"Failed to load checkpoint: {e}")
        st.stop()

    meta = load_metadata(ckpt_path)
    st.markdown(f"**Checkpoint:** `{ckpt_path.name}`")
    st.markdown(f"**Parameters:** {n_params:,}")
    if meta.get("trained_at"):
        st.markdown(f"**Trained:** {meta['trained_at']}")
    if meta.get("val_accuracy") is not None:
        st.markdown(f"**Val accuracy:** {meta['val_accuracy']*100:.1f}%")
    if meta.get("config"):
        st.markdown(f"**Config:** `{meta['config']}`")

    st.divider()
    st.subheader("Sample data")
    sample_dir = PROJECT_ROOT / "demo" / "sample_data"
    samples = sorted(p for p in sample_dir.glob("*.csv") if not p.name.startswith("_"))
    sample_choice = "—"
    if samples:
        st.caption("Pick one to load instead of uploading.")
        sample_choice = st.selectbox(
            "Sample dataset", ["—"] + [s.name for s in samples], label_visibility="collapsed"
        )


# ----- Main: input row -----
left, right = st.columns([1, 1])

with left:
    st.subheader("1 · Load a dataset")
    uploaded = st.file_uploader(
        "Drop a CSV here", type=["csv"],
        help="Numeric columns only. NaN cells are treated as missing.",
    )
    if uploaded is None and sample_choice != "—":
        uploaded_bytes = (sample_dir / sample_choice).read_bytes()
        upload_name = sample_choice
    elif uploaded is not None:
        uploaded_bytes = uploaded.getvalue()
        upload_name = uploaded.name
    else:
        uploaded_bytes = None
        upload_name = None

    analyze = st.button(
        "Analyze",
        type="primary",
        use_container_width=True,
        disabled=uploaded_bytes is None,
    )

with right:
    st.subheader("How it works")
    st.markdown(
        "Lacuna is a transformer + mixture-of-experts model trained on real survey "
        "tabular bases with synthetic missingness mechanisms applied. It computes a "
        "calibrated **posterior probability** over MCAR / MAR / MNAR by combining "
        "(a) the missingness pattern, (b) per-mechanism reconstruction likelihood, and "
        "(c) value-conditional features. From data alone, the mechanism is mathematically "
        "underdetermined (Molenberghs et al.) — Lacuna's value is the calibrated "
        "probability, not a categorical answer."
    )

if not analyze or uploaded_bytes is None:
    st.info("Upload a CSV (or pick a sample) and hit **Analyze** to get a verdict.")
    st.stop()


# =============================================================================
# Pipeline
# =============================================================================

st.divider()
st.subheader("2 · Walking through the analysis")

try:
    loaded = csv_to_dataset(uploaded_bytes, upload_name, max_rows=MODEL_DEFAULTS["max_rows"])
except Exception as e:
    st.error(f"Could not parse CSV: {e}")
    st.stop()

dataset = loaded.dataset

if dataset.d > MODEL_DEFAULTS["max_cols"]:
    st.warning(
        f"Dataset has {dataset.d} columns; the model supports "
        f"{MODEL_DEFAULTS['max_cols']}. Only the first will be used."
    )

overview = missingness_overview(dataset)
if overview["n_missing"] == 0:
    st.error(
        "No missing values found in the dataset. Lacuna classifies *missingness* — "
        "the data must contain NaN cells. If your CSV uses a sentinel "
        "(e.g. -999, 'NA'), convert those to NaN first."
    )
    st.stop()

with st.status("Running Lacuna…", expanded=True) as status:
    st.write(f"Parsed **{upload_name}** → {dataset.n} rows × {dataset.d} columns")
    if loaded.dropped_columns:
        preview = ", ".join(f"`{c}`" for c in loaded.dropped_columns[:6])
        more = "…" if len(loaded.dropped_columns) > 6 else ""
        st.write(f"Dropped {len(loaded.dropped_columns)} non-numeric column(s): {preview}{more}")
    if loaded.subsampled_from:
        st.write(f"Subsampled to {dataset.n} rows (from {loaded.subsampled_from}).")
    st.write(
        f"Missing cells: **{overview['n_missing']:,} / {overview['n_total']:,}** "
        f"({overview['pct_missing']:.1f}%)"
    )
    time.sleep(0.4)

    st.write("**Per-column missing rate** (cross-column variance is one of the model's features):")
    miss_df = pd.DataFrame({
        "column": overview["feature_names"],
        "missing_rate": overview["per_col_rate"],
    }).set_index("column")
    st.bar_chart(miss_df, height=180)
    time.sleep(0.4)

    if dataset.d >= 2:
        st.write("**Cross-column missingness correlation** "
                 "(MAR/MNAR patterns tend to show structured correlations):")
        corr = cross_column_corr(dataset)
        corr_df = pd.DataFrame(
            corr,
            index=overview["feature_names"],
            columns=overview["feature_names"],
        )
        st.dataframe(
            corr_df.style.background_gradient(cmap="RdBu_r", vmin=-1, vmax=1).format("{:.2f}"),
            use_container_width=True,
            height=min(60 + 30 * dataset.d, 360),
        )
        time.sleep(0.4)

    st.write("**Tokenizing and running the model…**")
    t0 = time.time()
    result = run_model(model, dataset)
    elapsed = time.time() - t0
    st.write(f"Forward pass: **{elapsed*1000:.0f} ms** on CPU.")

    status.update(label="Analysis complete", state="complete", expanded=False)


# =============================================================================
# Verdict — probabilistic framing
# =============================================================================

st.divider()
st.subheader("3 · Posterior")

p = result["p_class"]
p_mcar, p_mar, p_mnar = p[0], p[1], p[2]
recon = result.get("recon_errors", {}) or {}
norm_h = result["normalized_entropy"]
top_class = result["predicted_class_name"]
top_prob = result["confidence"]

# Surface real pipeline errors (e.g. calibration file missing or
# unparseable). Calibration is the only post-hoc artifact we still load.
cal_err = result.get("calibration_error")
if cal_err:
    if cal_err.startswith("calibration file not found"):
        st.info(
            "**Calibration not installed on this machine.** Showing the model's raw posterior. "
            "To enable calibration, copy `lacuna_survey/deployment/calibration.json` to this "
            "machine (produced by `python -m lacuna_survey.calibrate`).",
            icon="ℹ️",
        )
    else:
        st.error(f"Calibration failed: {cal_err}", icon="🛑")

# === Headline: posterior probabilities ===
prob_df = pd.DataFrame({
    "mechanism": list(CLASS_NAMES),
    "probability": p,
}).set_index("mechanism")
st.write(
    "**Posterior probability over missingness mechanisms** — "
    "each bar is *Lacuna's belief that this mechanism generated your missingness*, "
    "given the data and learned domain priors."
)
st.bar_chart(prob_df, height=220)

# === Decisiveness assessment ===
# Map normalized entropy → human description.
# norm_h = 0 → fully decisive (one class at 1.0); norm_h = 1 → uniform.
if norm_h < 0.40:
    decisiveness = "**Decisive.**"
    decisiveness_body = (
        f"The posterior is concentrated on **{top_class}** "
        f"({top_prob*100:.1f}%). Lacuna has strong evidence under its priors."
    )
elif norm_h < 0.75:
    decisiveness = "**Leaning, with non-trivial uncertainty.**"
    leaders = sorted(zip(CLASS_NAMES, p), key=lambda x: -x[1])[:2]
    second_class, second_prob = leaders[1]
    decisiveness_body = (
        f"**{top_class}** is most likely ({top_prob*100:.1f}%) but **{second_class}** "
        f"retains {second_prob*100:.1f}% posterior weight. The data does not strongly "
        f"distinguish between them — treat the leading class as a hypothesis, not a verdict."
    )
else:
    decisiveness = "**Genuinely uncertain.**"
    decisiveness_body = (
        "The posterior is spread across multiple mechanisms. From the data alone, "
        "Lacuna cannot reliably distinguish between them — this is the Molenberghs "
        "identifiability floor in action. Examine the per-mechanism evidence below "
        "and bring domain knowledge to the decision."
    )
st.markdown(f"{decisiveness} {decisiveness_body}")

# === Per-mechanism reconstruction evidence ===
if recon:
    st.write(
        "**How well does each mechanism explain your data?** "
        "Each Lacuna head reconstructs your dataset under that mechanism's "
        "assumptions; lower error = the data is highly self-consistent under that mechanism."
    )
    head_to_class = {"mcar": "MCAR", "mar": "MAR", "self_censoring": "MNAR"}
    rec_rows = []
    for k, v in recon.items():
        rec_rows.append({"mechanism": head_to_class.get(k, k), "reconstruction_error": v})
    rec_df = pd.DataFrame(rec_rows).set_index("mechanism")
    # Sort to match class display order
    rec_df = rec_df.reindex(["MCAR", "MAR", "MNAR"])
    st.bar_chart(rec_df, height=180)

    # Interpretive sentence based on which head fits best
    best_head = min(recon.items(), key=lambda kv: kv[1])
    best_class = head_to_class.get(best_head[0], best_head[0])
    others = sorted(recon.values())
    if len(others) >= 2 and others[0] > 0 and others[1] / max(others[0], 1e-9) > 5:
        ratio = others[1] / max(others[0], 1e-9)
        st.caption(
            f"The **{best_class}** head fits {ratio:.0f}× better than the next-closest "
            f"mechanism. Strong likelihood evidence under the {best_class} assumption."
        )
    else:
        st.caption(
            "Reconstruction errors are similar across heads — multiple mechanisms "
            "are roughly equally consistent with the observed data."
        )

# === Suggested next step ===
st.write("**Suggested next step**")
if p_mnar >= 0.50:
    st.info(
        f"**MNAR signal dominant** (P(MNAR) = {p_mnar*100:.1f}%). Standard imputation "
        "(mean, MICE, FIML) will be biased to the extent that the missingness depends on "
        "unobserved values. Use sensitivity analysis (Heckman selection, pattern-mixture "
        "models) and report results across plausible MNAR assumptions.",
    )
elif p_mnar >= 0.25:
    st.info(
        f"**Mixed signal — non-trivial MNAR weight** (P(MNAR) = {p_mnar*100:.1f}%). "
        "MICE / multiple imputation under MAR is defensible as a primary analysis but "
        "report a sensitivity analysis with MNAR plausible scenarios. The reconstruction "
        "evidence above tells you whether this is a borderline call or strongly MAR.",
    )
elif p_mar >= 0.60:
    st.info(
        f"**MAR-dominant** (P(MAR) = {p_mar*100:.1f}%). Multiple imputation (MICE, Amelia II) "
        "or likelihood-based methods (EM, FIML) are statistically defensible. Use observed "
        "covariates that predict missingness as imputation predictors.",
    )
elif p_mcar >= 0.60:
    st.info(
        f"**MCAR-dominant** (P(MCAR) = {p_mcar*100:.1f}%). Complete-case analysis is valid; "
        "simple imputation (mean, listwise deletion) is acceptable. Verify the mechanism "
        "is plausibly random (e.g. planned-missing rotated-booklet design).",
    )
else:
    st.info(
        "No mechanism dominates the posterior. Treat the leading class as a working "
        "hypothesis only; report sensitivity analyses across MAR and MNAR assumptions, "
        "and use domain knowledge to inform the modeling choice.",
    )


# =============================================================================
# Details (collapsible)
# =============================================================================

with st.expander("Show full details", expanded=False):
    cols = st.columns(2)

    with cols[0]:
        st.markdown("**Posterior probabilities**")
        rows = [
            {"mechanism": name, "p(mechanism | data)": f"{prob*100:.2f}%"}
            for name, prob in zip(CLASS_NAMES, p)
        ]
        st.dataframe(pd.DataFrame(rows).set_index("mechanism"), use_container_width=True)
        if result.get("calibration_applied"):
            st.caption(
                "Post-hoc calibration applied (vector scaling fit on real-survey anchors). "
                f"Raw posterior: MCAR={result['p_class_raw'][0]*100:.1f}%, "
                f"MAR={result['p_class_raw'][1]*100:.1f}%, "
                f"MNAR={result['p_class_raw'][2]*100:.1f}%."
            )
        st.markdown(
            f"**Entropy:** {result['entropy']:.3f} / {result['max_entropy']:.3f} "
            f"(normalized {result['normalized_entropy']:.2f})"
        )

    with cols[1]:
        st.markdown("**Reconstruction error per mechanism head**")
        if recon:
            recon_rows = [
                {"head": head_to_class.get(k, k), "mean error": f"{v:.5f}"}
                for k, v in recon.items()
            ]
            st.dataframe(pd.DataFrame(recon_rows).set_index("head"), use_container_width=True)
            st.caption(
                "Lower = the data is highly self-consistent under that mechanism's "
                "reconstruction model — a likelihood-evidence signal independent of the "
                "gate's posterior."
            )

    st.markdown("**Bayes risk by action** (for the legacy traffic-light view)")
    risks = result["expected_risks"]
    min_risk = min(risks)
    action_rows = []
    for label, risk in zip(["Green (assume MCAR)", "Yellow (assume MAR)", "Red (assume MNAR)"], risks):
        action_rows.append({
            "action": label,
            "expected_risk": f"{risk:.3f}" + ("  ← min" if risk == min_risk else ""),
        })
    st.dataframe(pd.DataFrame(action_rows).set_index("action"), use_container_width=True)
    st.caption(
        "Bayes-optimal action under symmetric loss. The probabilistic verdict above "
        "supersedes this for borderline cases."
    )

    st.markdown("**Raw JSON**")
    st.code(json.dumps(result, indent=2), language="json")
